canopen_vcan:
    bustype: socketcan
    channel: vcan0
    bitrate: 500000
    nodes: [{local: false, eds_location: 'eds_files/CargoDash.eds'}]
    raw_can_data_logging: false

canopen_serial:
    bustype: slcan
    channel: /dev/ttyACM0
    bitrate: 250000
    nodes: []
    raw_can_data_logging: false
    #TODO: whatever needs to be in "nodes" field
