canopen_example:
    bustype: socketcan
    channel: can0
    bitrate: 500000
    nodes: [{local: false, eds_location: 'eds_files/slave_node_example.eds', node_properties: {id: 5,
        name: 'Front view object distance', type: 0}}]
    max_speed_in_ms: 3
    raw_can_data_logging: false

canopen_vcan:
    bustype: socketcan
    channel: vcan0
    bitrate: 500000
    nodes: [{local: false, eds_location: 'eds_files/Arduino1.eds', node_properties: {id: 5,
        name: 'Front view object distance', type: 0}}]
    max_speed_in_ms: 3
    raw_can_data_logging: false

canopen_serial:
    bustype: slcan
    channel: /dev/ttyACM0
    bitrate: 500000
    nodes: []
    max_speed_in_ms: 3
    raw_can_data_logging: false
    #TODO: whatever needs to be in "nodes" field
