canopen_example:
    bustype: socketcan
    channel: can0
    bitrate: 500000
    nodes: [{local: false, eds_location: 'eds_files/slave_node_example.eds', node_properties: {id: 5,
        name: 'Front view object distance', type: 0}}]
    max_speed_in_ms: 3
    raw_can_data_logging: {
        enabled: true,
        # The value is the amount in raw can messages.
        # Implementation saves raw can messages up until buffer's value. 
        buffer: 1024,
        # At every n-th message update shared memory
        shm_update_interval_threshold: 100

    }

canopen_vcan:
    bustype: socketcan
    channel: vcan0
    bitrate: 500000
    nodes: [{local: false, eds_location: 'eds_files/Arduino1.eds', node_properties: {id: 5,
        name: 'Front view object distance', type: 0}}]
    max_speed_in_ms: 3
    raw_can_data_logging: {
        enabled: false,
        # The value is the amount in raw can messages.
        # Implementation saves raw can messages up until buffer's value. 
        buffer: 1024,
        # At every n-th message update shared memory
        shm_update_interval_threshold: 100
    }

canopen_serial:
    bustype: slcan
    channel: /dev/ttyACM0
    bitrate: 500000
    nodes: []
    max_speed_in_ms: 3
    raw_can_data_logging: {
        enabled: true,
        buffer: 1024,
        # At every n-th message update shared memory
        shm_update_interval_threshold: 100
    }
    #TODO: whatever needs to be in "nodes" field
